Repository CSE112-sp22-group9/cse112-sp22-group9, pull requests merged in 2022-05, with the labels that each got.

#8 Fix Styling for BackendInit.js
  .eslintrc.json
  source/Backend/BackendInit.js
  source/Backend/MockData.json
Labels: documentation

#12 NL-39 feat(doc): complete L3 system flow diagram
  specs/110SysDiag.drawio.png
Labels: documentation

#26 Nl 22 variables calendar dustin
  source/Index/Calendar.js
  source/Index/IndexJS.js
  source/Login/LoginJS.js
  source/MonthlyOverview/MonthlyJS.js
Labels: bug, CI/CD pipeline

#20 Nl 37 Exploratory Firebase Testing
  .eslintrc.json
  package-lock.json
  package.json
  source/Backend/FirebaseInit.js
  source/Backend/firebase-src/firebase-app.js.map
  source/Backend/firebase-src/firebase-app.min.js
  source/Backend/firebase-src/firebase-auth.min.js
  source/Backend/firebase-src/firebase-database.js.map
  source/Backend/firebase-src/firebase-database.min.js
  source/Login/Login.html
  source/Login/Login.js
Labels: enhancement

#36 Nl 28 frontend login sign up page sophia alice
  source/Images/dino2.jpg
  source/Login/Images/dino2.jpg
  source/Login/Login.html
  source/Login/Login.js
  source/Login/LoginJS.js
  source/Login/LoginStyles.css
Labels: enhancement, issue

#37 added adrs for Jira and Firebase decisions
  specs/adr/5-18-22-Firebase-Hosting.md
  specs/adr/5-18-22-Jira.md
Labels: documentation

#61 Nl 57 add google login shawn
  source/Backend/FirebaseInit.js
  source/Login/Images/google_sign_in.svg
  source/Login/Login.html
  source/Login/Login.js
  source/Login/LoginStyles.css
Labels: issue, Backend

#55 Nl 35 deployment site dustin
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  firebase.json
  mil-notes/IndexedDBstorage.md
  mil-notes/firebase-deploy.md
  package-lock.json
  package.json
  source/Backend/updatedMockData.json
  source/Login/Login.html
  source/index.html
Labels: documentation, CI/CD pipeline

#54 Nl 47 crud notes alice
  .eslintrc.json
  source/Backend/BackendInit.js
  source/Backend/FirebaseInit.js
  source/DailyOverview/DailyJS.js
  source/DailyOverview/DailyOverview.html
  source/Index/Index.html
  source/MonthlyOverview/MonthlyJS.js
Labels: issue, Backend

#68 NL-64 Weekly Panel Backend
  source/Backend/BackendInit.js
  source/Backend/updatedMockData.js
  source/Login/Login.js
  source/Login/WeeklyOverview/WeeklyJS.js
  source/Login/WeeklyOverview/WeeklyOverview.html
Labels: Backend

#69 NL-65 Notes Panel Backend
  source/Backend/BackendInit.js
  source/Login/Login.js
  source/Login/WeeklyOverview/WeeklyJS.js
Labels: Backend
