Repository CSE112-sp22-group9/cse112-sp22-group9, pull requests merged in 2022-06, with the labels that each got.

#101 Nl 59 defining user settings alice
  source/Backend/BackendInit.js
  source/Login/Login.js
  source/Login/WeeklyOverview/WeeklyJS.js
  source/Login/WeeklyOverview/WeeklyOverview.html
  source/Login/WeeklyOverview/WeeklyStyles.css
Labels: issue, Backend

#98 NL-90 Connect Dailyjs to Backend
  source/Backend/BackendInit.js
  source/Backend/updatedMockData.js
  source/Backend/updatedMockData.json
  source/DailyOverview/DailyJS.js
  source/DailyOverview/DailyOverview.html
  source/DailyOverview/DailyStyles.css
  source/DailyOverview/bullet.js
  source/Index/Calendar.js
  source/Index/IndexJS.js
  source/Login/Login.js
  source/Login/LoginJS.js
  source/Login/WeeklyOverview/WeeklyJS.js
  source/Login/WeeklyOverview/WeeklyOverview.html
  source/Login/WeeklyOverview/WeeklyStyles.css
  source/MonthlyOverview/MonthlyJS.js
  source/YearlyOverview/YearlyJS.js
Labels: enhancement, Backend

#119 NL-109 Better Event Listener Handling for Monthly/Yearly Goals
  source/Calendar/Calendar.js
  source/Login/WeeklyOverview/Calendar.js
Labels: Backend

#114 NL-99 Implement password strength check
  source/Backend/BackendInit.js
  source/Login/Login.html
  source/Login/Login.js
  source/Login/WeeklyOverview/Calendar.html
  source/WeeklyOverview/Weekly.js
Labels: issue, frontend

#126 NL-125 Add Theme to DailyOverview
  source/DailyOverview/Daily.js
  source/Login/Login.html
  source/Login/Login.js
  source/WeeklyOverview/Weekly.js
Labels: enhancement, Backend, frontend

#138 NL-134 Fix Photo Album Back Button
  source/DailyOverview/Daily.js
Labels: bug, Backend

#139 NL-136 Add Modal Submit on Enter Keypress
  source/Calendar/Calendar.js
Labels: enhancement, frontend

#144 NL-143 Check if User is Logged-In
  source/Backend/BackendInit.js
  source/Calendar/Calendar.html
  source/Calendar/Calendar.js
  source/Calendar/CalendarStyles.css
  source/DailyOverview/Daily.js
  source/DailyOverview/DailyOverview.html
  source/DailyOverview/DailyStyles.css
  source/Login/Login.html
  source/Login/Login.js
  source/WeeklyOverview/Weekly.js
  source/WeeklyOverview/WeeklyOverview.html
  source/WeeklyOverview/WeeklyStyles.css
Labels: enhancement, Backend, frontend

#140 General Styling/Logic/Organization Changes + Bug Fixes
  source/Backend/BackendInit.js
  source/Backend/FirebaseInit.js
  source/Calendar/Calendar.js
  source/Calendar/CalendarStyles.css
  source/DailyOverview/Daily.js
  source/DailyOverview/DailyOverview.html
  source/DailyOverview/DailyStyles.css
  source/General-JS/bullet.js
  source/Images/Add.svg
  source/Images/Delete.svg
  source/Images/Done.svg
  source/Images/Edit.svg
  source/Images/Event.svg
  source/Images/Heart.svg
  source/Images/House.svg
  source/Images/Pencil.svg
  source/Images/Star.svg
  source/Login/Login.html
  source/Login/Login.js
  source/Login/LoginStyles.css
  source/WeeklyOverview/Weekly.js
  source/WeeklyOverview/WeeklyOverview.html
  source/WeeklyOverview/WeeklyStyles.css
Labels: bug, documentation, enhancement, Backend, frontend

#145 Nl 91 e2e test dustin
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/firebase-test-branch-hosting-merge.yml
  .github/workflows/testing.yml
  deprecated-source/tests/OldPuppTests.test.js
  package-lock.json
  package.json
  source/tests/PuppTests.test.js
Labels: CI/CD pipeline

#152 Nl 148 forgot password backend
  source/Login/Login.html
  source/Login/Login.js
  source/Login/LoginStyles.css
Labels: issue
